parse_input_task:
  description: >
    data =>
    Client: {Client}
    Contractor: {Contractor}
    raw_description: {raw_description}
    current_year: {current_year}
    ###
    Analyze this description and extract structured project information, including inferred fields like:
    - project_title
    - client_name
    - contractor_name
    - project_goals
    - deliverables
    - timeline
    - revision_policy
    - estimated cost or budget (infer based on description or use market data if possible)
  expected_output: >
    A detailed structured JSON object containing the project blueprint extracted from a single paragraph of input.
  agent: InputParser_Agent

build_scope_outline_task:
  description: >
    data =>
    current_year: {current_year}
    ###
    Build a document outline customized for the project type, referencing best practices for SoW structure in the relevant domain.
  expected_output: >
    An adaptive list of Scope of Work sections tailored to the project.
  agent: ScopeBuilder_Agent

estimate_budget_task:
  description: >
    data =>
    current_year: {current_year}
    ###
    Estimate the project's budget based on scope, deliverables, and timeline.
    Use web data if needed to find average prices and validate input budget.
  expected_output: >
    A numeric estimated budget figure and justification.
  agent: BudgetEstimator_Agent

generate_content_task:
  description: >
    data =>
    current_year: {current_year}
    ###
    Generate detailed content for each section of the SoW using the project blueprint.
    Include deliverables, acceptance criteria, objectives, and any implied constraints.
  expected_output: >
    A full draft of the Scope of Work, one section per heading, with comprehensive and easy-to-understand content.
  agent: ContentWriter_Agent

insert_policy_clauses_task:
  description: >
    data =>
    current_year: {current_year}
    ###
    Add legal and operational clauses to the draft document.
    If price or duration is mentioned, cross-check average market rates using web search.
  expected_output: >
    A complete Scope of Work draft with professional clauses for:
    - IP ownership
    - Revisions
    - Payment terms
    - Confidentiality
    - Termination
  agent: PolicyAgent

quality_review_task:
  description: >
    data =>
    current_year: {current_year}
    ###
    Perform a professional edit and quality check.
    Ensure there's no contradiction, grammar issue, or missing data.
  expected_output: >
    A polished SoW document, cleaned and corrected.
  agent: QualityCheck_Agent

format_sow_document_task:
  description: >
    data =>
    current_year: {current_year}
    ###
    Convert the content into clean Markdown format for export or PDF rendering.
    Ensure bullet points, tables, and spacing are professional.
  expected_output: >
    A formatted Markdown version of the Scope of Work, ready to be rendered or exported.
  agent: Formatter_Agent
