parse_input_task:
  description: >
    data=>
    Client: {Client}
    Contractor: {Contractor}
    raw_description: {raw_description}
    current_year: {current_year}
    ####
    Parse a short paragraph and extract structured information about the project including:
    - project_title (inferred from goals)
    - client_name
    - contractor_name
    - project_goals
    - timeline
    - deliverables (if listed or implied)
    - revision_policy (if mentioned)
    - budget (if possible to infer)
  expected_output: >
    A structured JSON object containing inferred project details from a short paragraph of text.
  agent: InputParser_Agent

build_scope_outline_task:
  description: >
    data=>
    current_year: {current_year}
    ####
    Use the structured input to build a detailed Scope of Work outline.
    The outline should contain all major sections typically found in an SoW document.
  expected_output: >
    A list of section headers for the SoW document, including: Overview, Parties Involved,
    Objectives, Deliverables, Timeline, Payment Terms, Revisions, IP Ownership, Confidentiality,
    Communication Plan, Termination Clause, and Signatures.
  agent: ScopeBuilder_Agent

generate_content_task:
  description: >
    data=>
    current_year: {current_year}
    ###
    Using the outline and structured input, create detailed content under each section.
    The content should be professional, project-specific, and easy to understand.
  expected_output: >
    A full Scope of Work draft with content under each section header, ready for policy insertion.
  agent: ContentWriter_Agent

insert_policy_clauses_task:
  description: >
    data=>
    current_year: {current_year}
    ####
    Enhance the Scope of Work by adding important legal and operational clauses
    (e.g., revision limits, IP ownership, confidentiality terms, and payment conditions).
  expected_output: >
    A refined Scope of Work that includes standardized and professional clauses in the appropriate sections.
  agent: PolicyAgent

quality_review_task:
  description: >
    data=>
    current_year: {current_year}
    ####
    Perform a quality check of the SoW. Review it for clarity, consistency, grammar, and completeness.
    Make any necessary edits for professionalism and accuracy.
  expected_output: >
    A polished, high-quality version of the Scope of Work that is ready for formatting and sharing.
  agent: QualityCheck_Agent

format_sow_document_task:
  description: >
    data=>
    current_year: {current_year}
    ####
    Format the final content into structured Markdown format.
    Ensure headers, bullets, and spacing are clean and consistent.
    The final output should be ready for PDF export or sharing.
  expected_output: >
    A fully formatted Markdown version of the Scope of Work document, including all required sections.
  agent: Formatter_Agent
